spring:
  application:
    name: infoplatform_user
  datasource:
    url: jdbc:mysql://www.siengine.com:3306/recruit_website?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: xymt1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 9005
  servlet:
    context-path: /friend/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://tssb:xixi@localhost:9000/eureka/

swagger:
  base-path: /**
  enabled: true
  exclude-path: /error/**,/actuator/**

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
