spring:
  application:
    name: infoplatform-friend
  datasource:
    url: jdbc:mysql://localhost:3306/im_friend?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  resources:
    static-locations: /static/
  mvc:
    static-path-pattern: /**

server:
  port: 9005
  servlet:
    context-path: /friend/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://tssb:xixi@localhost:9000/eureka/

swagger:
  base-path: /**
  enabled: true
  exclude-path: /error/**,/actuator/**

mybatis-plus:
  typeEnumsPackage: com.infoplatform.friend.server.enums
  mapper-locations: classpath*:/mapper/**/*.xml

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: Semaphore
