spring:
  application:
    name: infoplatform-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xymt2016/config.git
  rabbitmq:
    host: localhost
server:
  port: 9001
management:
  endpoints:
    jmx:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://tssb:xixi@localhost:9000/eureka/
  instance:
    prefer-ip-address: true