#spring:
#  application:
#    name: infoplatform_user
#
#server:
#  port: 9003
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone:  http://tssb:xixi@localhost:9000/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#swagger:
#  base-path: /**
#  enabled: true
#  exclude-path: /error/**,/actuator/**
#
#jwt:
#  config:
#    key: itcast
#    ttl: 360000